# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 829)
        self.central = QtWidgets.QWidget(MainWindow)
        self.central.setObjectName("central")
        self.central_grid_layout = QtWidgets.QGridLayout(self.central)
        self.central_grid_layout.setObjectName("central_grid_layout")
        self.image_plots_layout = QtWidgets.QWidget(self.central)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(
            self.image_plots_layout.sizePolicy().hasHeightForWidth()
        )
        self.image_plots_layout.setSizePolicy(sizePolicy)
        self.image_plots_layout.setObjectName("image_plots_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.image_plots_layout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.raw_window = GraphicsLayoutWidget(self.image_plots_layout)
        self.raw_window.setObjectName("raw_window")
        self.verticalLayout.addWidget(self.raw_window)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.exposure_label = QtWidgets.QLabel(self.image_plots_layout)
        self.exposure_label.setObjectName("exposure_label")
        self.gridLayout.addWidget(self.exposure_label, 0, 0, 1, 1)
        self.auto_exposure = QtWidgets.QPushButton(self.image_plots_layout)
        self.auto_exposure.setObjectName("auto_exposure")
        self.gridLayout.addWidget(self.auto_exposure, 0, 2, 1, 1)
        self.exposure_time = QtWidgets.QSpinBox(self.image_plots_layout)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.exposure_time.sizePolicy().hasHeightForWidth()
        )
        self.exposure_time.setSizePolicy(sizePolicy)
        self.exposure_time.setObjectName("exposure_time")
        self.gridLayout.addWidget(self.exposure_time, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.central_grid_layout.addWidget(self.image_plots_layout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.central)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exposure_label.setText(_translate("MainWindow", "Exposure time (us)"))
        self.auto_exposure.setText(_translate("MainWindow", "Auto exposure"))


from pyqtgraph import GraphicsLayoutWidget
